version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/golang:1.11
      - image: circleci/postgres:10
        environment:
          POSTGRES_USER: test_user
          POSTGRES_DB: test_ledgerdb
          POSTGRES_PASSWORD: test_password
    working_directory: /go/src/github.com/RealImage/QLedger
    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: sudo apt-get update && sudo apt-get install postgresql-client
      - run:
          name: Build
          command: go build
      - run:
          name: "Enforce Go Formatted Code" # https://circleci.com/blog/enforce-build-standards/#enforce-code-formatting
          command: "! go fmt ./... 2>&1 | read"
      - run:
          name: "Identify Vet Errors"
          command: go vet ./...
      - run:
          name: Test
          command: psql $TEST_DATABASE_URL < schema.sql; go test ./... -race -p=1
          environment:
            TEST_DATABASE_URL: "postgres://test_user@0.0.0.0:5432/test_ledgerdb?sslmode=disable"
  
  build_and_deploy:
    working_directory: /go/src/github.com/RealImage/QLedger
    steps:
      - checkout
      - run:
          name: "Build qledger_koho docker image"
          command: docker build --build-arg AWS_RDS_DB_URL=${AWS_RDS_DB_URL_STAGE}-t qledger_koho .

orbs:
  aws-ecr: circleci/aws_ecr@6.12.2
  aws-ecs: circleci/aws_ecs@1.3.0
          
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build_and_test
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image
          requires:
            - build_and_test
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update
          requires:
            - aws-ecr/build-and-push-image
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"